changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - wontfix
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - "*"
